[env:xteink_x4]
; Use pioarduino (Arduino Core 3.x) like CrossPoint does
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-c3-devkitc-02
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
board_build.flash_size = 16MB

lib_deps =
  EInkDisplay=symlink://open-x4-sdk/libs/display/EInkDisplay
  InputManager=symlink://open-x4-sdk/libs/hardware/InputManager
  BatteryMonitor=symlink://open-x4-sdk/libs/hardware/BatteryMonitor

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DEINK_DISPLAY_SINGLE_BUFFER_MODE
