[env:xteink_x4]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; ESP32-C3 settings for Xteink X4
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
board_build.flash_size = 16MB

; Libraries
lib_deps =
  EpdScreenController=symlink://open-x4-sdk/libs/display/EpdScreenController
  BatteryMonitor=symlink://open-x4-sdk/libs/hardware/BatteryMonitor

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DSHELF_SERVER_URL=\"\"
  -DWIFI_SSID=\"\"
  -DWIFI_PASS=\"\"
